// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSbqYDO3fS8LWuaMF327vpaa2zO2xtf6k',
    appId: '1:996116177747:web:5d2a43e4efdc67ce15b7a6',
    messagingSenderId: '996116177747',
    projectId: 'boundless-416723',
    authDomain: 'boundless-416723.firebaseapp.com',
    storageBucket: 'boundless-416723.appspot.com',
    measurementId: 'G-ZJX0NYQMG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8H6h0yRnJrGIpaHEB2GYoZW4XivloGfg',
    appId: '1:996116177747:android:f9e1c90b95b4dc0e15b7a6',
    messagingSenderId: '996116177747',
    projectId: 'boundless-416723',
    storageBucket: 'boundless-416723.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_XKuNceRDsXQB_u6T9yCU--XAq5j9tmg',
    appId: '1:996116177747:ios:40f6cf0b874fbe9f15b7a6',
    messagingSenderId: '996116177747',
    projectId: 'boundless-416723',
    storageBucket: 'boundless-416723.appspot.com',
    iosBundleId: 'com.example.boundless',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_XKuNceRDsXQB_u6T9yCU--XAq5j9tmg',
    appId: '1:996116177747:ios:40f6cf0b874fbe9f15b7a6',
    messagingSenderId: '996116177747',
    projectId: 'boundless-416723',
    storageBucket: 'boundless-416723.appspot.com',
    iosBundleId: 'com.example.boundless',
  );
}
